# Introduction

Compiled languages like Fortran and C are natively much faster than Python, but not necessarily so when Python is bound to them. Using packages like Cython enables Python to interface with C code and pass information from the C program to Python and vice versa through memory. This allows Python to be on par with the faster languages when necessary and to use legacy code.

### NumPy 

<li>Numerical processing through multi-dimentional ndarrays.</li>
<li>Element by element operation a.k.a Broadcasting.</li>
<li>Arrays can be modified in size dynamically.</li>
<li>Applying 'masking' to hide certain elements instead of creating a new array.</li>

### SciPy

<li>SciPy is built on NumPy Array Framework</li>

## Why NumPy?

Python stores data in several different ways, but the most popular methods are lists and dictionaries.The Python list object can store nearly any type of Python object as an element. But operating on the elements in a list can only be done through iterative loops, which is computationally inefficient in Python.

The NumPy package enables users to overcome the shortcomings of the Python lists by providing a data storage object called ndarray. As an aftermath mathematical operations is very fast on data.




Tuples eg: 1,2,3,4   OR (1,2,3,4)
List [1,2,3,4]
Dictionaries 


#### How to add constant (5 in our case) to each items in a List?

In [3]:
my_list = [1,3,5,7,9,2,4,6,8]
my_list

[1, 3, 5, 7, 9, 2, 4, 6, 8]

#### Processing via FOR LOOP

In [4]:
new_list=[]
for i in my_list:
    new_list.append(i+5)
new_list

[6, 8, 10, 12, 14, 7, 9, 11, 13]

#### Processing via List Comprehension

In [5]:
new_list1=[i+6 for i in my_list]
new_list1

[7, 9, 11, 13, 15, 8, 10, 12, 14]

#### Import Numpy Library and create a numpy array

In [6]:
import numpy as np
arr=np.array(my_list)
arr

array([1, 3, 5, 7, 9, 2, 4, 6, 8])

In [7]:
type(arr)

numpy.ndarray

##### Broadcasting in numpy array

In [8]:
arr+5

array([ 6,  8, 10, 12, 14,  7,  9, 11, 13])

##### Broadcasting in Numpy

<li> Numpy arrays can be modified in size dynamically. The ndarray is similar to lists, but rather than hetrogenious they are homogenious e.g., all elements must be floats, integers, or strings. With this limitation aside, operation on numpy array is very fast than its list counterpart

In above example, Numpy adds scaler value 5, to each items of array, and is blazingly fast (we will compare execution time later)

But what will happen if items in input data is not of one type?

#### Homogeneity & Type Casting



In [9]:
list2 = [1,5,'c',4]
arr2 = np.array(list2)
arr2

array(['1', '5', 'c', '4'], 
      dtype='<U21')

In [10]:
# Exclamatory symbol '!' is used to run a command has a command line arrgument
! ls

Hello_Python.ipynb           hello.txt
NumPy Basics.ipynb           imdb_1000.csv
Pandas Basics.ipynb          my_array.npy
Pima_Predication.ipynb       mynew_array.npz
Python Pandas Test.ipynb     ufo.csv
SciPy - Linear Algebra.ipynb untitled.txt
chipotle.tsv


#### Initial Placeholders

In [11]:
#Return a 2-D array with ones on the diagonal and zeros elsewhere.
f= np.eye(2,dtype=np.int16)
f

array([[1, 0],
       [0, 1]], dtype=int16)

In [56]:
#Return a new array of given shape and type, filled with zeros.
a= np.zeros((3,3),dtype=np.int16)
a


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [65]:
#Built-in magic commands : https://ipython.org/ipython-doc/dev/interactive/magics.html
#Defining custom magics : https://ipython.org/ipython-doc/dev/config/custommagics.html
%timeit [val+5 for val in a]
#The major advantage is that you don't have to import timer.timeit, and run the code multiple times
#to figure out which is the better approach; 
#%timeit will automatically calculate number of runs required for your code based 
#on a total of 2 seconds execution window.

The slowest run took 9.08 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.2 µs per loop


In [13]:
#Return evenly spaced values within a given interval.
b=np.arange(10,25,2,dtype=np.int16)
b

array([10, 12, 14, 16, 18, 20, 22, 24], dtype=int16)

In [14]:
#Return evenly spaced numbers over a specified interval.
np.linspace(0,10,5,dtype=np.int16)

array([ 0,  2,  5,  7, 10], dtype=int16)

In [15]:
#Return random floats in the half-open interval [0.0, 1.0).
c=np.random.random(size=6)
c

array([ 0.42946958,  0.52736735,  0.9603984 ,  0.46923864,  0.29770402,
        0.6337462 ])

In [16]:
#Return a new array of given shape and type, without initializing entries.
d=np.empty((2,2),dtype=np.int16)
d

array([[-6591,  6700],
       [18342, 16356]], dtype=int16)

In [17]:
#Return a new array of given shape and type, filled with `fill_value`.
e=np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

### I/O
#### Saving and Loading On Disk

In [18]:
#Save an array to a binary file in NumPy ``.npy`` format.
np.save('my_array',arr)

In [19]:
#Save several arrays into a single file in uncompressed ``.npz`` format.
np.savez('mynew_array',arr,b,c)

In [20]:
#Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.
np.load('my_array.npy')

array([1, 3, 5, 7, 9, 2, 4, 6, 8])

### Saving and Loading Text Files

In [21]:
! more hello.txt

1
2
3
4

>

<b>FORMATS</b><br>
The first character specifies kind of data & remaining characters specify the no. of bytes per item, except for Unicode
<li>
'?' boolean
<li>'b' (signed) byte
<li>'B' unsigned byte
<li>'i' (signed) integer
<li>'u' unsigned integer
<li>'f' floating-point
<li>'c' complex-floating point
<li>'m' timedelta
<li>'M' datetime
<li>'O' (Python) objects
<li>'S', 'a'    zero-terminated bytes (not recommended)
<li>'U' Unicode string
<li>'V' raw data (void)Load data from a text file.
</li>

In [22]:
table = np.loadtxt('hello.txt',dtype=np.int16)        
table

array([1, 2, 3, 4], dtype=int16)

#### Inspecting Your Array

In [23]:
a

array([0, 0, 0], dtype=int16)

In [24]:
#Array dimensions
a.shape

(3,)

In [25]:
#Return the number of items in a container.
len(a)

3

In [26]:
#Number of array dimensions
a.ndim

1

In [27]:
#Number of array elements
a.size

3

In [28]:
#Datatype of the array elememts
a.dtype

dtype('int16')

In [29]:
#Name of the datatype
a.dtype.name

'int16'

In [30]:
#Convert an array to a different type
b.astype(float)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.])

#### Array Mathematics
##### Arithmetic Operations

In [31]:
f= np.array([(1,2),(3,4)])
g=np.array([(5,6,3),(7,8,4),(4,10,2)]) #Two dimentional array
z=np.array([[(5,6,3),(7,8,4),(4,10,2)],[(1,2,3),(4,5,6),(7,8,9)]]) #Three dimentional array
#h=a-b OR np.subtract(f,g) : Subtraction 
#h=f+g OR np.add(f+g) : Addition
#h=f/g OR np.divide(f,g) : Division
#h=f*g OR np.multiply(f,g) : Multipilcation
#np.exp(f) : Exponentiation
#np.sqrt(f) : Squre root
#np.sin(f) : Print sines of an array
#np.cos(f) : Element-wise cosine
#np.log(a) : Element-wise natural logarithms
#e.dot(f) : Dot Product

#### Comparision

In [32]:
#Element wise comparison
f==g

/Users/apple/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


False

In [33]:
#Element wise comparison
f>1

array([[False,  True],
       [ True,  True]], dtype=bool)

In [34]:
#Array-wise Comparison
np.array_equal(f,g)

False

#### Aggregate Functions

In [35]:
#f.sum() Array-wise sum
#f.min() Array-wise minimum value
#Axis=0 implies Operation on Column
#Axis=1 implies Operation on Rows

In [36]:
#Minimum Value in every row since axis =1
g.min(axis=1)
#g.min(axis=0) Minuium value is every column

array([3, 4, 2])

In [37]:
#Cumulative sum of the elements
g.cumsum(axis=0) 

array([[ 5,  6,  3],
       [12, 14,  7],
       [16, 24,  9]])

In [38]:
#Mean of a matrix i.e sum of all elements divided by No. of elements
g.mean()

5.4444444444444446

In [39]:
#Compute the standard deviation along the specified axis.
np.std(g)

2.408831487630978

#### Copying Array

In [40]:
#New view of array with the same data.
h=g.view()
#Return an array copy of the given object. <NOT SURE>
np.copy(g,'K')
#Return a copy of the array.
h=g.copy()
h


array([[ 5,  6,  3],
       [ 7,  8,  4],
       [ 4, 10,  2]])

#### Sorting Arrays

In [41]:
#a.sort(axis=-1, kind='quicksort', order=None)
#Sort an array, in-place.
#g.sort(axis=1,kind='quicksort')
g

array([[ 5,  6,  3],
       [ 7,  8,  4],
       [ 4, 10,  2]])

#### Subsetting, Slicing, Boolean Indexing

In [42]:
#Selecting the a specific element with there index
print (g[2,1])


10


In [43]:
b

array([10, 12, 14, 16, 18, 20, 22, 24], dtype=int16)

In [44]:
#Slicing from the index[startindex:stopIndex-1]
# NOTE: Using ':' we mention ROW Index, the second element after ',' represent coloumn Index
b[0:5]

array([10, 12, 14, 16, 18], dtype=int16)

In [45]:
g[0:3,1] # [starting rowIndex,endingRowIndex-1,coloumnIndex]

array([ 6,  8, 10])

In [46]:
g[2] #Slicing with respect to Row

array([ 4, 10,  2])

In [47]:
g[:2] # Select all elements from [beginningRowIndex:N-1 RowsIndex] 

array([[5, 6, 3],
       [7, 8, 4]])

In [48]:
g[1:] # Select all elements from [beginningRowIndex 1:TILL LAST ROW INDEX] 

array([[ 7,  8,  4],
       [ 4, 10,  2]])

In [49]:
g[::-1] # Reversing an array

array([[ 4, 10,  2],
       [ 7,  8,  4],
       [ 5,  6,  3]])

In [50]:
g[g<3] #Select elements from 'g' greater than 3 'Boolean Indexing'

array([2])

#### Array Manipulation

In [51]:
#Transposing an Array
#Def: Permute the dimensions of an array.
#Permute:submit to a process of alteration, rearrangement, or permutation.
print (np.transpose(g)) 
#or h.T


[[ 5  7  4]
 [ 6  8 10]
 [ 3  4  2]]


In [52]:
b

array([10, 12, 14, 16, 18, 20, 22, 24], dtype=int16)

In [53]:
#Changing array shape
#Return a flattened array.
print (z.ravel())

[ 5  6  3  7  8  4  4 10  2  1  2  3  4  5  6  7  8  9]


In [54]:
#Returns an array containing the same data with a new shape. 
g.reshape(9,1)

array([[ 5],
       [ 6],
       [ 3],
       [ 7],
       [ 8],
       [ 4],
       [ 4],
       [10],
       [ 2]])

In [55]:
#Adding / Removing Elements
x=z.resize((2,2))
x